# Here general configuration things are stored, which can be used as inputs to workflow rules
# within the snakemake workflow. The layout is standard yaml and will be available in snakemake
# as a dictionary

# a relative path to output
output_dir: output/

## Weather generator parameters ##
# some other parameters for generating random meteorological forcing with a very simple model
start_date: 2022-09-01
end_date: 2022-12-31
# we use constant evaporation in this simple model
evapo: 1.5
# transition probability of dry to wet day is 20% Change to try out other values
p_01: 0.2
# transition probability of wet to dry day is 30%
p_10: 0.3
# random numbers are multiplied by this number to ensure we get a certain amount reasonable for mm per day 
multiplier: 50
# when rainfall is lower than 1.0 mm per day, it is considered a dry day
rainfall_thres: 1.0
## Hydrology model parameters ##
hydro_parameters:
  # below we define some parameters for a very simple hydrological model, stocks in mm and time scales in days
  interception: 1
  storage_1_max: 100
  alpha: 0.6
  k_fast: 7
  k_slow: 150
  storage_1: 40
  storage_2: 20