# Here general configuration things are stored, which can be used as inputs to workflow rules
# within the snakemake workflow. The layout is standard yaml and will be available in snakemake
# as a dictionary

# a relative path to output
output_dir: output/

## Weather generator parameters ##
# some other parameters for generating random meteorological forcing with a very simple model
start_date: 2022-09-01
end_date: 2022-10-01
# we use constant evaporation in this simple model
evapo: 1.5
# about 60 percent of days should be dry
dry_day_fraction: 0.6
# random numbers are multiplied by this number to ensure we get a certain amount reasonalbe for mm per day 
multiplier: 50

## Hydrology model parameters ##
hydro_parameters:
  # below we define some parameters for a very simple hydrological model, stocks in mm and time scales in days
  interception: 1
  storage_1_max: 100
  alpha: 0.6
  k_fast: 7
  k_slow: 150
  storage_1: 40
  storage_2: 20